### ISSUE TITLE
Christian: segfaulting Python script that calls np.einsum

### ISSUE THREAD

**Issue by willfurnass** [ooominds/RSE-ticketing#7]
@kuchenrolle found that attempts to run a particular Python script segfaulted in a non-deterministic way.  

The most computationally expensive part of this script is a call to [numpy.einsum](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.einsum.html) within a loop.  We therefore suspected that the segfault was associated with compiled parts of NumPy or with MKL functions called by NumPy.  

Debugging compiled code that is called from Python code is non-trivial so instead we *tried* upgrading from NumPy 1.13.x to 1.14.y and from MKL 2017.a to MKL 2018.b in the conda environment Christian had created on ShARC.

However, this resulted in a further issue: conda 4.3.17 on ShARC, as it's presently configured, is not aware of the latest versions of NumPy and the MKL.  A manually-installing Miniconda in `/data/$USER/` on ShARC (that provides conda 4.5.4) was able to find, download and install the latest NumPy and MKL.  We believe the issue is that conda 4.3.17 is not aware of the following channels: 

* `https://repo.anaconda.com/pkgs/main/linux-64`
* `https://repo.anaconda.com/pkgs/main/noarch`

as discovered by comparing the output of `conda info` between the central and `/data/$USER` conda installs.

Christian has now configured his ShARC job so that it will use his personal `/data/$USER` conda install; he's to report back to confirm whether using the latest NumPy and MKL have fixed the original issue.

**Comment by kuchenrolle** [comment]
So, I've looked into this a little more over the last couple of days and the situation looks even weirder than we thought. Using the current MKL and numpy versions did not fix the issue.

As it turns out, the most expensive operation in terms of time is not the calculation between the two matrices that uses the einsum function, but instead it is the loading of the actual matrices that takes several times as long.

The segmentation fault likewise does not occur at that calculation, but when some pair of matrices are being loaded with [xarray.open_dataarray](http://xarray.pydata.org/en/stable/generated/xarray.open_dataarray.html). In particular, this also happens when the calculations are not done at all. Loading all the matrices individually does not result in any errors, neither does loading the specific two matrices on which the segmentation fault occurs. Which combination of matrices the segmentation fault occurs on also changes when some of the preceding combinations are skipped, meaning that the same combination that did segfault will not do so in a different context, so the problem appears to be cumulative rather than tied to a specific combination of matrices.

When I deleted the currently loaded weight matrices and forced garbage collection at the end of every iteration of the loop (after each combination of matrices was loaded and compared), two things happened: The error disappeared and there was a significant increase in speed. I am assuming that something goes wrong when the matrices are loaded with xarray via netcdf (which is a hidden dependency that doesn't show up with `conda list` but can be imported in python nonetheless - the version is not the newest one either).

So I have the results now, though this not really a satisfying solution. Maybe you could look into that, @willfurnass?

**Comment by willfurnass** [comment]
Where does your code live?

**Comment by kuchenrolle** [comment]
Everything is in /shared/ooominds1/Shared/benchmark_modelling_choices

The script that worked is /scripts/correlate_2.py, called with /scripts/correlate_gc.sh

**Comment by willfurnass** [comment]
GitHub repo created for scripts: https://github.com/ooominds/benchmark_modelling_choices

Modified code to use context managers when reading xaarrays from NetCDF files; ensures that resources are properly closed when no longer needed.  Was then able to run the full correlation process on all 1540 pairs of files without encountering segfaults.  Took ~8h8m to complete on ShARC (run `qacct -j 1454819` on ShARC for details).
